from . import sales_order
from . import sale_order_cancel_wizard
from . import cancel_sales_dashboard
from . import cancel_sales_main
from . import cancel_sales_data_history
from . import sale_order_confirm_delete_wizard
from . import res_config_settings
from . import sale_order_extension
from . import cancel_sales_date_range_wizard
from . import dashboard_image 